[package]
name = "omega-automata"
authors = ["Konrad Winslow"]
version = "0.1.0"
description = "Algorithms on omega (infinite word) automata and LTL logic."
license = "Apache-2.0"
edition = "2024"
repository = "https://github.com/I-mikan-I/omega-automata"
keywords = ["model_checking", "automata", "ltl", "deicision_procedures", "theory"]
categories = ["algorithms", "data-structures", "mathematics", ]
documentation = "https://docs.rs/omega-automata"

[dependencies]
bitvec = "1.0.1"
color = "0.3.2"
rand = "0.9.2"
